### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by akurdunkar**

### CODE REVIEW

**Comment by akurdunkar** [comment]
I was trying to build this but it didn't work with some minor changes I have built it and also the aur package doesn't work this changes also helped me with the pkgbuild

**Comment by marmistrz** [comment]
I'm no longer using C::B and I have thus orphaned the AUR package.

**Comment by akurdunkar** [comment]
thanks for letting me know, I was wondering what I should do when code::blocks says that the plugin is made for a different sdk of codeblocks ?

**Comment by akurdunkar** [comment]
```
Scanning for plugins in /home/aditya/.local/share/codeblocks/plugins
/home/aditya/.local/share/codeblocks/plugins/cbVike.so: not loaded (missing symbols?)
Loaded 0 plugins
Info[Warning]: One or more plugins were not loaded.
This usually happens when a plugin is built for
a different version of the Code::Blocks SDK.
Check the application log for more info.
```

To give more context here is the error

**Pull request closed without merging**
